{% set name = "furl" %}
{% set version = "2.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "c0e0231a1feee2acd256574b7033df3144775451c610cb587060d6a0d7e0b621" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - six >=1.8.0
    - orderedmultidict >=1.0

test:
  imports:
    - furl

about:
  home: https://github.com/gruns/furl
  license_file: LICENSE.md
  license: PUBLIC-DOMAIN
  summary: 'URL manipulation made simple.'
  dev_url: https://github.com/gruns/furl
  doc_url: https://github.com/gruns/furl

extra:
  recipe-maintainers:
    - pmlandwehr
