{% set name = "furl" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a6188fe2666c484a12159c18be97a1977a71d632ef5bb867ef15f54af39cc4e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - six >=1.8.0
    - orderedmultidict >=1.0

test:
  imports:
    - furl
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gruns/furl
  license_file: LICENSE.md
  license: Unlicense
  summary: URL manipulation made simple.
  dev_url: https://github.com/gruns/furl
  doc_url: https://github.com/gruns/furl

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
