{% set name = "furl" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7dba33eafbee7dbc83963534b25e72f816cced48ac53191ee60bfcc62933918

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - six >=1.8.0
    - orderedmultidict >=1.0

test:
  imports:
    - furl
  commands:
    - pip check
  requires: 
    - pip

about:
  home: https://github.com/gruns/furl
  license_file: LICENSE.md
  license: PUBLIC-DOMAIN
  summary: 'URL manipulation made simple.'
  dev_url: https://github.com/gruns/furl
  doc_url: https://github.com/gruns/furl

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
