travis:
  secure:
    BINSTAR_TOKEN: g5gO/exhN27kacukvttSYEnP8gXZwLP1NhFkuV0s+Ax6/RgfIK+9PbZ1A+/C3uloKsxeVdrFk1vhlKrZSndXtijR2hJbCHD9jgV/hNn1yXrHgWSCn1Oh82dVO3/ApnPJ9eIVvtb7TF+S7qDM6O2fBDY51zD4ibXSKjorxbWaJekMFNfaIMogJw64dYqfiyGU4+RHoLAZ7OSOt/YpyvQ7lAtso1S1rfC63U3T7/wIbCHDg2OQcL2bYWBPn1svqI2NycnnPT8uco6bij6u14ACQXEnFOMRvkjq7LJ1mAuXs1byXIPLwyZEIY61K4bNJTaucVSeHPZDrx9yHwtjzdcD7AGWxMQ4tCUafKYuT2D/v2kmLuyuwfCI/gRr/jBIVwv8DTgN3Tk3CS8bXTHhvM8ubWJMHEJQt008v+FMtKkXesNJGWdp28ZzmxWsPi+4uoPrmpycoaNlYRuSTa68cVz/f/BjO6zNS0FXgi9nHJcuj/ku7wOXO5Uf0lRvHY9e02PRKdg6x9i3BqJ+tRPqjVO5ZJ8i9AHMDE6hNYJrBPH4a+f+xbHmg6Q5tu5EF8sOtGOLyM5/DOK6qQeR9YCoFSFCY6V0y1hHhpoUrNCijWOEVyyM3/eAntcMlFB4bcMJtPm+V/aZn+8b2bF8l9vd1VVaxbEH+Ybme7yoZ7K2JQC+slo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
